#+LATEX_HEADER: \usepackage{minted}
#+LATEX_HEADER: \usepackage[margin=1in]{geometry}

* High-Level Description of Project

The high-level goal of our project is to build an algorithm to ~reduce
noise~ in biological networks to improve the performance of various
~information mining tasks~ on the denoised network.

COPIED: We want to build an algorithm for improving the
signal-to-noise ratio of undirected, weighted networks.

Some of the ~information mining tasks~ considered are listed as
follows:
  - Network clustering
  - Function prediction
  - Low dimensional embedding
  - Link prediction

Evidently, the performance metrics differ between tasks. We will first
consider the task of function prediction.

* Running Code Locally
Although not required to use the code, the project uses Jupyter
Notebooks to visualize, tinker, and play with the code. It is highly
recommended, but if you just want to use the code in some pipeline
then you only need to install the correct packages.

** Dependencies
The project has a few dependencies:
  - python 3.7+
  - matplotlib
  - scipy
  - numpy
  - pandas
 
The easiest way to set this all up is with conda, which you can
install through miniconda or anaconda. Then, run the following
commands:

#+BEGIN_EXPORT latex
\begin{minted}[mathescape, 
xleftmargin=2pt, 
xrightmargin=2pt, 
style=autumn, 
framesep=3mm,
frame=lines
]{sh}
conda create --name denoise # Creates a new conda environment named denoise
conda activate denoise # Activates the environment
conda install jupyterlab matplotlib scipy numpy pandas # Installs packages into environment
\end{minted}
#+END_EXPORT

** Running project locally 
For running Jupyter notebook locally, start at the root of the directory
of the project and run the following commands:

#+BEGIN_EXPORT latex
\begin{minted}[mathescape, 
xleftmargin=2pt, 
xrightmargin=2pt, 
style=autumn, 
framesep=3mm,
frame=lines
]{sh}
conda activate denoise # Activates environment with jupyter notebook
jupyter notebook # Runs notebook locally
\end{minted}
#+END_EXPORT

Everything should now work as expected!

** Running project remotely on cluster
Sometimes it is necessary to run the project on the cluster. To do
this, we run the notebook remotely on the cluster and use an SSH
tunnel to forward the notebook to your laptop.

[[https://amber-md.github.io/pytraj/latest/tutorials/remote_jupyter_notebook][Jupyter notebook remote tutorial]]

#+BEGIN_EXPORT latex
\begin{minted}[mathescape, 
xleftmargin=2pt, 
xrightmargin=2pt, 
style=autumn, 
framesep=3mm,
frame=lines
]{sh}
ssh -N -f -L localhost:[LOCAL]:localhost:[REMOTE] username@your_remote_host_name
ssh -N -f -L localhost:8888:localhost:4000 hschmi02@login.cluster.tufts.edu
\end{minted}
#+END_EXPORT

* Using as a Python package
The conda environment ~denoise~ contains the python package, so it
should be as easy as activating the environment to use the code. To
update the package, run the following commands:
#+BEGIN_EXPORT latex
\begin{minted}[mathescape, 
xleftmargin=2pt, 
xrightmargin=2pt, 
style=autumn, 
framesep=3mm,
frame=lines
]{sh}
git pull
source activate denoise
pip install .
\end{minted}
#+END_EXPORT

